----METADATA----
CREATE TABLE df_orders (
    order_id NUMBER,
    order_date DATE,
    ship_mode VARCHAR2(50),
    segment VARCHAR2(50),
    country VARCHAR2(50),
    city VARCHAR2(50),
    state VARCHAR2(50),
    postal_code NUMBER(20),
    region VARCHAR2(50),
    category VARCHAR2(50),
    sub_category VARCHAR2(50),
    product_id VARCHAR2(50),
    quantity NUMBER,
    discount NUMBER,
    sale_price NUMBER,
    profit NUMBER
);

SELECT * FROM DF_ORDERS;
DESC DF_ORDERS;
DROP TABLE DF_ORDERS;
----METADATA----

--1. find top 10 highest reveue generating products 
SELECT PRODUCT_ID,SUM(SALE_PRICE) AS SALES
FROM DF_ORDERS
GROUP BY PRODUCT_ID
ORDER BY SALES DESC
FETCH FIRST 10 ROWS ONLY;

--2. find top 5 highest selling products in each region
SELECT * FROM 
(SELECT REGION,PRODUCT_ID,SALES,ROW_NUMBER() OVER(PARTITION BY REGION ORDER BY SALES DESC) AS RN 
FROM (SELECT REGION,PRODUCT_ID,SUM(SALE_PRICE) AS SALES
FROM DF_ORDERS
GROUP BY REGION,PRODUCT_ID))
WHERE RN<6;

--3. find month over month growth comparison for 2022 and 2023 sales eg : jan 2022 vs jan 2023
SELECT MONTH,SALES_2022,SALES_2023,SALES_2023 - SALES_2022 AS GROWTH,ROUND((SALES_2023 - SALES_2022)/SALES_2022*100,2)||'%' AS PERCENTAGE FROM (
SELECT MONTH,SUM(CASE YEAR WHEN 2022 THEN SALES ELSE 0 END)AS SALES_2022,
SUM(CASE YEAR WHEN 2023 THEN SALES ELSE 0 END) AS SALES_2023
FROM
(SELECT EXTRACT(MONTH FROM ORDER_DATE) AS MONTH,EXTRACT(YEAR FROM ORDER_DATE) AS YEAR,SUM(SALE_PRICE) AS SALES
FROM DF_ORDERS
GROUP BY EXTRACT(MONTH FROM ORDER_DATE),EXTRACT(YEAR FROM ORDER_DATE)
ORDER BY YEAR,MONTH)
GROUP BY MONTH
ORDER BY MONTH);

--4. for each category which month had highest sales 
SELECT * FROM (
SELECT CATEGORY,YEAR,MONTH,SALES,ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY SALES DESC ) AS RANK
FROM (
SELECT CATEGORY,EXTRACT(YEAR FROM ORDER_DATE)AS YEAR,EXTRACT(MONTH FROM ORDER_DATE)AS MONTH,SUM(SALE_PRICE) SALES FROM DF_ORDERS
GROUP BY CATEGORY,EXTRACT(YEAR FROM ORDER_DATE),EXTRACT(MONTH FROM ORDER_DATE))
ORDER BY CATEGORY,YEAR,MONTH)
WHERE RANK = 1;

--5. which sub category had highest growth by profit in 2023 compare to 2022
SELECT SUB_CATEGORY,SALES_2022,SALES_2023,SALES_2023 - SALES_2022 AS GROWTH FROM (
SELECT SUB_CATEGORY,SUM(CASE EXTRACT(YEAR FROM ORDER_DATE) WHEN 2022 THEN SALE_PRICE ELSE 0 END)AS SALES_2022,
SUM(CASE EXTRACT(YEAR FROM ORDER_DATE) WHEN 2023 THEN SALE_PRICE ELSE 0 END) AS SALES_2023 
FROM DF_ORDERS 
GROUP BY SUB_CATEGORY)
ORDER BY GROWTH DESC
FETCH FIRST 1 ROW WITH TIES
;



